ratebeer/config/routes.rb
Ratebeer::Application.routes.draw do

  resources :memberships

  resources :beer_clubs

  root 'breweries#index'
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :delete]
  resources :users
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
end

ratebeer/app/models/user.rb
class User < ActiveRecord::Base
	include RatingAverage
	has_many :ratings, dependent: :destroy
	has_many :beers, through: :ratings
	has_many :memberships, dependent: :destroy
	has_many :clubs, through: :memberships, source: :beer_club
	has_secure_password

	validates :username, uniqueness: true, length: { minimum: 3, maximum: 15 }
	validates :password, format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{4,}\z/, message: "Password must contain atleast one uppercase letter, a number and be longer than 3 characters." }

	
	
end

ratebeer/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
     session[:user_id] = nil
    @user.destroy
    respond_to do |format|
      format.html { redirect_to :root }
      format.json { head :no_content }
	end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
     params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

ratebeer/app/helpers/users_helper.rb
module UsersHelper
end

ratebeer/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

 <% if not @user.new_record? %>
<h2>Change password of <%= @user.username %></h2>
<% end %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ratebeer/app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :back %>

ratebeer/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

ratebeer/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

ratebeer/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @user.username %>
</h2>

<p>
<% if not @user.memberships.empty? %>
Part of <%=pluralize(@user.memberships.count, 'beer club') %>:
<% end %>
<% @user.clubs.each do |r| %> 
<td><%= link_to  r.name, beer_club_path(r) %></td>
<% end %>
</p>

<p>
 <% if @user.ratings.empty? %>
 No ratings yet.
 <% else %>
 Has made <%=pluralize(@user.ratings.count, 'rating') %>.
 Average rating: <%= @user.average_rating %>
<% end %>
</p>



<table>
 <thead>
	<tr>
	<th>Beer</td>
	<th>Rating</td>
	</tr>
 </thead>

  <tbody>
    <% @user.ratings.each do |r| %>
      <tr>
	<td><%= r.beer.name %></td> 
    	<td> | <%= r.score %></td>
	<% if @user == current_user %>
	<td><%= link_to 'Delete', r, method: :delete, data: {confirm: 'Are ya shuuure?'} %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</p>

<p>
	<% if @user == current_user %>
	<%= link_to 'Edit', edit_user_path(@user) %> |
	<td><%= link_to 'Delete User', user_path(current_user) , method: :delete, data: {confirm: 'Are ya shuuure?'} %></td>
	<% end %>
<%= link_to 'Back', :back %>
</p>