config/routes.rb
Ratebeer::Application.routes.draw do
  
  resources :beer_clubs
  root 'breweries#index'
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resource :session, only: [:new, :create, :delete]
  resources :memberships, only: [:new, :create, :destroy]
  resources :users
  resources :places, only:[:index, :show]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  post 'places', to:'places#search'
  delete 'signout', to: 'sessions#destroy'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
 resources :users do
    put 'freeze_account', on: :member
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
	include RatingAverage
	has_many :ratings, dependent: :destroy
	has_many :beers, through: :ratings
	has_many :memberships, dependent: :destroy
	has_many :clubs, through: :memberships, source: :beer_club
	has_secure_password

	validates :username, uniqueness: true, length: { minimum: 3, maximum: 15 }
	validates :password, format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{4,}\z/, message: "Password must contain atleast one uppercase letter, a number and be longer than 3 characters." }

	def self.most_rated(n)
	sorted = User.all.sort_by{ |b| -(b.ratings.count ||0) }
	sorted.take(n)
	end
	def self.favorite_styles(n)
	sorted = User.all
	end

def favorite_beer
return nil if ratings.empty?
ratings.order(score: :desc).limit(1).first.beer
end
def favorite_brewery
return nil if ratings.empty?
brewery_ratings = rated_breweries.inject([]) do |ratings, brewery|
ratings << {
name: brewery,
rating: rating_of_brewery(brewery) }
end
brewery_ratings.sort_by { |brewery| brewery[:rating] }.reverse.first[:name]
end
def favorite_style
return nil if ratings.empty?
style_ratings = rated_styles.inject([]) do |ratings, style|
ratings << {
name: style,
rating: rating_of_style(style) }
end
style_ratings.sort_by { |style| style[:rating] }.reverse.first[:name]
end
def rated_breweries
ratings.map{ |r| r.beer.brewery }.uniq
end
def rated_styles
ratings.map{ |r| r.beer.style }.uniq
end
def rating_of_brewery(brewery)
ratings_of_brewery = ratings.select do |r|
r.beer.brewery == brewery
end
ratings_of_brewery.map(&:score).sum / ratings_of_brewery.count
end
def rating_of_style(style)
ratings_of_style = ratings.select do |r|
r.beer.style == style
end
ratings_of_style.map(&:score).sum / ratings_of_style.count
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :freeze_account]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user or current_user.admin and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
     session[:user_id] = nil
    @user.destroy
    respond_to do |format|
      format.html { redirect_to :root }
      format.json { head :no_content }
	end
    end
  end
  def freeze_account
	if current_user.admin
	user = User.find(params[:id])
	user.update_attribute :iced, (not user.iced)
	user.save
	new_status = user.iced? ? "frozen" : "melted"	
	redirect_to :back, notice:"user is now #{new_status}"
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
     params.require(:user).permit(:username, :password, :password_confirmation, :iced)
  end
end

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if user.admin? and user.iced? %>
            <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h2>
  <%= @user.username %>
  <% if @user.iced %><p class="bg-info">account frozen</p><%end%>
</h2>

<p>
<% if not @user.memberships.empty? %>
Part of <%=pluralize(@user.memberships.count, 'beer club') %>:
<% end %>
<% @user.clubs.each do |r| %> 
<td><%= link_to  r.name, beer_club_path(r) %></td>
<% end %>
</p>

<p>
 <% if @user.ratings.empty? %>
 No ratings yet.
 <% else %>
<p>
 Favorite beer style: <%= @user.favorite_style %>.
 Favorite brewery: <%= @user.favorite_brewery %>
</p>
 Has made <%=pluralize(@user.ratings.count, 'rating') %>.
 Average rating: <%= @user.average_rating %>.
<% end %>
</p>

<table class="table table-hover">
 <thead>
	<tr>
	<th>Beer</td>
	<th>Rating</td>
	</tr>
 </thead>

  <tbody>
    <% @user.ratings.each do |r| %>
      <tr>
	<td><%= r.beer.name %></td> 
    	<td><%= r.score %></td>
	<% if @user == current_user %>
	<td><%= link_to 'Delete', r, method: :delete, data: {confirm: 'Are ya shuuure?'} %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</p>

<p>
	<% if @user == current_user %>
	<%= link_to 'Edit', edit_user_path(@user) %> |
	<td><%= link_to 'Delete User', user_path(current_user) , method: :delete, data: {confirm: 'Are ya shuuure?'} %></td>
	<% end %>
<%= link_to 'Back', :back %>
</p>
<p> 
<% if current_user and current_user.admin %>
<%= link_to "Freeze account", freeze_account_user_path(@user.id), method: :put, class: "btn btn-primary" %>
<%end%>
</p>