config/routes.rb
Ratebeer::Application.routes.draw do
  
  resources :beer_clubs
  root 'breweries#index'
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resource :session, only: [:new, :create, :delete]
  resources :memberships, only: [:new, :create, :destroy]
  resources :users
  resources :places, only:[:index, :show]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  post 'places', to:'places#search'
  delete 'signout', to: 'sessions#destroy'

  resources :breweries do
    post 'toggle_activity', on: :member
  end
 resources :users do
    put 'freeze_account', on: :member
  end
  
end

app/models/style.rb
class Style < ActiveRecord::Base
	include RatingAverage
	has_many :beers
	has_many :ratings, through: :beers
	validates :beerstyle, presence: true

	def to_s
	self.beerstyle
	end

	def self.top(n)
	sorted_by_rating_in_desc_order = Style.all.sort_by{ |b| -(b.average_rating||0) }
	sorted_by_rating_in_desc_order[0..(n-1)]
	end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
before_action :set_style, only: [:show, :edit, :update]

  def index
	@styles = Style.all
  end
  
  def new
    @style = Style.new
  end
  
   def create
    @style = Style.new params.require(:style).permit(:beerstyle, :description)

    if current_user.nil?
          redirect_to signin_path, notice:'you should be signed in'
    elsif @style.save
      redirect_to styles_path
    else
      render :new
    end
  end
  def edit
  end

  def show
  end

   def destroy
    if current_user.admin
    rating = Style.find(params[:id])
    rating.destroy
    redirect_to styles_path
    end
  end

  def update
    respond_to do |format|
      if style_params[:beerstyle].nil? and @style.update(style_params)
        format.html { redirect_to @style, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def style_params
     params.require(:style).permit(:beerstyle, :description)
  end
  def set_style
   @style = Style.find(params[:id])
  end

end

app/views/styles/edit.html.erb
<%= form_for(@style) do |f| %>

 <% if not @style.new_record? %>
<h2>Edit style</h2>
<% end %>

  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', :back %>

app/views/styles/index.html.erb
<h2>List of beerstyles</h2>
<p> Number of styles: <%= @styles.count %> </p>

<table class="table table-hover">
	<thead>
	<tr><th>Style</th></tr>
	</thead>
	
	 <% @styles.each do |style| %>  
	<tbody>
	<td><%= link_to style.beerstyle, style_path(style)%></td>
	</tbody>
	<% end %>	
 
</table>

<p>
<%if current_user %>
<%= link_to 'Add new style', new_style_path, class:"btn btn-primary" %>
<%end%>
</p>

app/views/styles/new.html.erb
<h2>New style</h2>

<%= form_for(@style) do |f| %>
    <% if @style.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@style.errors.count, "error") %> prohibited rating from being saved:</h2>

          <ul>
            <% @style.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    Beer style: <%= f.text_field :beerstyle %>
    Description: <%= f.text_field :description %>
    <%= f.submit %>
<% end %>

app/views/styles/show.html.erb
<h2>
  <%= @style.beerstyle %>
</h2>

<p>
<%= @style.description %>
</p>

<h3>List of beers:</h3>
<p>
<ul>
<% @style.beers.each do |b|  %>
<li><%= link_to b.name, beer_path(b) %> by <%= link_to b.brewery.name, brewery_path(b.brewery) %></li>
<% end %>
</ul>
</p>

<p>
<% if current_user %>
<%= edit_and_destroy_buttons(@style) %>
<%end%>
</p>